_BASE_: "../base_frcnn_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "./results/COCO/frcnn/frcnn_r101_fpn_COCO_concepts_zeros/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
CONCEPT:
  CONCEPT_FUSION: "zeros" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: TRUE
  APPLY_CONDITION_FROM_FILE: FALSE
  APPLY_FILTER: FALSE
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TRAIN: ("coco_2017_tuning_val",)
  # TEST: ("coco_2017_val_subset",)
  # TEST: ("coco_2017_val_powerset",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/COCO/frcnn/frcnn_r101_fpn_COCO_concepts_zeros/"