_BASE_: "base_dh_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "./results/COCO/dh/dh_swint_fpn_COCO_concepts_mul/model_final.pth"
  ATSS:
    NUM_CONVS: 0
CONCEPT:
  CONCEPT_FUSION: "mul" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: FALSE
  APPLY_CONDITION_FROM_FILE: FALSE
  APPLY_FILTER: FALSE
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  # TEST: ("coco_2017_val_subset",)
  # TEST: ("coco_2017_val_powerset",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/COCO/dh/dh_swint_fpn_COCO_concepts_mul/"