_BASE_: "../base_retinanet_VG878.yaml"
MODEL:
  WEIGHTS: "./results/VG/retinanet/retinanet_drigoni_r101_fpn_VG878/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("vg878_train",)
  TEST: ("vg878_val",)
OUTPUT_DIR: "./results/VG/retinanet/retinanet_drigoni_r101_fpn_VG878/"
