_BASE_: "../base_dh_VG_concepts.yaml"
MODEL:
  WEIGHTS: "./results/VG/dh/dh_swint_fpn_VG_concepts_cat/model_final.pth"
  ATSS:
    NUM_CONVS: 2
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: TRUE
  APPLY_CONDITION_FROM_FILE: FALSE
  ACTIVATE_CONCEPT_GENERATOR: FALSE
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/VG/dh/dh_swint_fpn_VG_concepts_cat/"