_BASE_: "../base_frcnn_COCO.yaml"
MODEL:
  WEIGHTS: "./results/COCO/frcnn/frcnn_r50_fpn_COCO_numfc4/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    FC_DIM: 2048 # standard=1024
    NUM_FC: 4 # standard=2
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TRAIN: ("coco_2017_tuning_val",)
  # TEST: ("coco_2017_val_subset",)
  # TEST: ("coco_2017_val_powerset",)
OUTPUT_DIR: "./results/COCO/frcnn/frcnn_r50_fpn_COCO_numfc4/"