_BASE_: "../base_frcnn_COCO.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    FC_DIM: 2048 # standard=1024
    NUM_FC: 6 # standard=2
OUTPUT_DIR: "./results/COCO/frcnn/frcnn_r50_fpn_COCO_numfc6/"