_BASE_: "../base_dh_OID.yaml"
MODEL:
  WEIGHTS: "./results/OID/dh/dh_swint_fpn_OID/model_final.pth"
  ATSS:
    NUM_CONVS: 2
DATASETS:
  TRAIN: ("oid_v4_train",)
  TEST: ("oid_v4_val",)
OUTPUT_DIR: "./results/OID/dh/dh_swint_fpn_OID/"