_BASE_: "../base_frcnn_COCO.yaml"
MODEL:
  WEIGHTS: "./results/COCO/frcnn/frcnn_drigoni_r101_fpn_COCO/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
  # TEST: ("coco_2017_val_subset",)
  # TEST: ("coco_2017_val_powerset",)
OUTPUT_DIR: "./results/COCO/frcnn/frcnn_drigoni_r101_fpn_COCO/"