_BASE_: "../base_frcnn_COCO.yaml"
MODEL:
  META_ARCHITECTURE: "drigoniGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
OUTPUT_DIR: "./results/COCO/frcnn/frcnn_drigoni_r101_fpn_COCO/"