_BASE_: "../base_dh_COCO.yaml"
MODEL:
  WEIGHTS: "./results/COCO/dh/dh_swint_fpn_COCO/model_final.pth"
  ATSS:
    NUM_CONVS: 2
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
OUTPUT_DIR: "./results/COCO/dh/dh_swint_fpn_COCO/"