_BASE_: "../base_retinanet_COCO.yaml"
MODEL:
  WEIGHTS: "./results/COCO/retinanet/retinanet_drigoni_r50_fpn_COCO/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
OUTPUT_DIR: "./results/COCO/retinanet/retinanet_drigoni_r50_fpn_COCO/"
