_BASE_: "../base_retinanet_VG_concepts.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
OUTPUT_DIR: "./results/VG/retinanet/retinanet_r101_fpn_VG_concepts_cat/"