_BASE_: "../base_retinanet_VG.yaml"
MODEL:
  WEIGHTS: "./results/VG/retinanet/retinanet_drigoni_r101_fpn_VG/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
OUTPUT_DIR: "./results/VG/retinanet/retinanet_drigoni_r101_fpn_VG/"
