_BASE_: "../base_dh_OID.yaml"
MODEL:
  WEIGHTS: "./results/OID/dh/dh_r50_fpn_OID/model_final.pth"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_dyhead_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  ATSS:
    NUM_CONVS: 2
DATASETS:
  TRAIN: ("oid_v4_train",)
  TEST: ("oid_v4_val",)
OUTPUT_DIR: "./results/OID/dh/dh_r50_fpn_OID/"