_BASE_: "../base_retinanet_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  DEPTH: 0
SOLVER:
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.01
  STEPS: [60000, 80000, 100000]
  MAX_ITER: 160000
  GAMMA: 0.1
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  WEIGHT_DECAY_NORM: 0.0
OUTPUT_DIR: "./results/COCO/retinanet/retinanet_r101_fpn_COCO_concepts_cat_depth0_comparison/"