_BASE_: "../base_retinanet_COCO.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
OUTPUT_DIR: "./results/COCO/retinanet/retinanet_r101_fpn_COCO/"