_BASE_: "../base_retinanet_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "./results/COCO/retinanet/retinanet_r101_fpn_COCO_concepts_cat_depth0/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  DEPTH: 0
SOLVER:
  IMS_PER_BATCH: 12
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.00001
  STEPS: []
  MAX_ITER: 18000
  GAMMA: 1.0
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.00001
  WEIGHT_DECAY_BIAS: 0.00001
  WEIGHT_DECAY_NORM: 0.0
OUTPUT_DIR: "./results/COCO/retinanet/retinanet_r101_fpn_COCO_concepts_cat_depth0_finetuning/"