_BASE_: "../base_retinanet_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "./results/COCO/retinanet/retinanet_r50_fpn_COCO_concepts_cat_deepsetv3/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: FALSE
  APPLY_CONDITION_FROM_FILE: FALSE
  ACTIVATE_CONCEPT_GENERATOR: FALSE
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
DEEPSETS:
  EMB: "random"
  MLP1_LAYERS: [150, 256, 256]
  MLP1_OUTPUT_DIM: 256 
  MLP2_LAYERS: [256, 256]
  OUTPUT_DIM: 256
OUTPUT_DIR: "./results/COCO/retinanet/retinanet_r50_fpn_COCO_concepts_cat_deepsetv3/"
