_BASE_: "../base_retinanet_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
DEEPSETS:
  MLP1_LAYERS: [150, 256]
  MLP1_OUTPUT_DIM: 256 
  MLP2_LAYERS: [256, 256]
  OUTPUT_DIM: 256
OUTPUT_DIR: "./results/COCO/retinanet/retinanet_r50_fpn_COCO_concepts_cat_deepsetv2/"