_BASE_: "base_dh_OID_concepts.yaml"
MODEL:
  WEIGHTS: "./results/OID/dh/dh_swint_fpn_OID_concepts_cat/model_final.pth"
  ATSS:
    NUM_CONVS: 2
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: FALSE
  APPLY_CONDITION_FROM_FILE: FALSE
  ACTIVATE_CONCEPT_GENERATOR: FALSE
DATASETS:
  TRAIN: ("oid_v4_train",)
  TEST: ("oid_v4_val",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/OID/dh/dh_swint_fpn_OID_concepts_cat/"