_BASE_: "../base_dh_COCO_concepts.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_fpn_dyhead_backbone"
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res3", "res4", "res5"]
  ATSS:
    NUM_CONVS: 2
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
OUTPUT_DIR: "./results/COCO/dh/dh_r101_fpn_COCO_concepts_cat/"