_BASE_: "../base_dh_VG.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  BACKBONE:
    NAME: "build_resnet_fpn_dyhead_backbone"
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res3", "res4", "res5"]
  ATSS:
    NUM_CONVS: 2
OUTPUT_DIR: "./results/VG/dh/dh_r101_fpn_VG/"