_BASE_: "../base_dh_VG.yaml"
MODEL:
  WEIGHTS: "./results/VG/dh/dh_r101_fpn_VG/model_final.pth"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_dyhead_backbone"
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  ATSS:
    NUM_CONVS: 2
DATASETS:
  TRAIN: ("vg_train",)
  TEST: ("vg_val",)
OUTPUT_DIR: "./results/VG/dh/dh_r101_fpn_VG/"