MODEL:
  META_ARCHITECTURE: "ConceptGeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  IMS_PER_BATCH: 16
  # BASE_LR: 0.02
  BASE_LR: 0.0025       # one 1 GPU
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
CONCEPT:
  FILE: './concept/coco_to_synset.json'
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: TRUE
  APPLY_CONDITION_FROM_FILE: FALSE
  EXTERNAL_CONCEPTS_FOLDER: './datasets/ewiser_concepts_COCO_valid/'
  ACTIVATE_CONCEPT_GENERATOR: TRUE
  DEPTH: 1
  UNIQUE: TRUE
DEEPSETS:
  EMB: 'wordnet'   # 'random' # 'wordnet'
  EMB_DIM: 150
  FREEZE: TRUE
  AGGREGATE: 'sum'
  OUTPUT_DIM: 256
EVALUATOR_TYPE: 'default'
VERSION: 2
SEED: 2022